// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClsEDKKMpDD-8-is2hLpk0t4ya8eB0a-k',
    appId: '1:293389518943:web:0c24cb562fee72cbb273ea',
    messagingSenderId: '293389518943',
    projectId: 'projobtracker-184ae',
    authDomain: 'projobtracker-184ae.firebaseapp.com',
    storageBucket: 'projobtracker-184ae.firebasestorage.app',
    measurementId: 'G-FLG2H225LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTOfsNEndAEXM2FQHfyLucSD9231uSo2A',
    appId: '1:293389518943:android:e00858d5c560c03cb273ea',
    messagingSenderId: '293389518943',
    projectId: 'projobtracker-184ae',
    storageBucket: 'projobtracker-184ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB__Kyx0ymmRB5BDDBsEbc7AQeQfUthgnQ',
    appId: '1:293389518943:ios:8b9ec072bbbcc1a3b273ea',
    messagingSenderId: '293389518943',
    projectId: 'projobtracker-184ae',
    storageBucket: 'projobtracker-184ae.firebasestorage.app',
    iosBundleId: 'com.example.proJobTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB__Kyx0ymmRB5BDDBsEbc7AQeQfUthgnQ',
    appId: '1:293389518943:ios:8b9ec072bbbcc1a3b273ea',
    messagingSenderId: '293389518943',
    projectId: 'projobtracker-184ae',
    storageBucket: 'projobtracker-184ae.firebasestorage.app',
    iosBundleId: 'com.example.proJobTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClsEDKKMpDD-8-is2hLpk0t4ya8eB0a-k',
    appId: '1:293389518943:web:78ac8ff67169b0d2b273ea',
    messagingSenderId: '293389518943',
    projectId: 'projobtracker-184ae',
    authDomain: 'projobtracker-184ae.firebaseapp.com',
    storageBucket: 'projobtracker-184ae.firebasestorage.app',
    measurementId: 'G-K6W6QPY8SS',
  );
}
