import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Firebase core
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI

import 'starting_page.dart';
import 'login_page.dart';
import 'create_account_page.dart';
import 'dashboard_screen.dart';
import 'charts_screen.dart';
import 'calendar_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Ensures binding before Firebase init
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  ); // Initializes Firebase with correct options
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Pro Job Tracker',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => StartingPage(),
        '/login': (context) => LoginPage(),
        '/create_account': (context) => CreateAccountPage(),
        '/dashboard': (context) => DashboardScreen(),
        '/charts': (context) => ChartsScreen(),
        '/calendar': (context) => CalendarPage(allJobs: []), // Provide an appropriate value for 'allJobs'
      },
    );
  }
}